### PR TITLE
Update AlwaysDay.php

### PR DESCRIPTION
**Pull request by Wertzui123**
Added a switch, no argument is needed for true anymore, and a succes message (I forgot it when you don't provide an arg, lol).

### CODE REVIEW

**Comment by DenielWorld** [comment]
Oh I see, since what default runs is the same as true it'll be the case for whenever the bool given is not false, but something else such as true etc. Did I get your point correctly here?

**Comment by Wertzui123** [comment]
It already was, but I made it with the switch

**Comment by Wertzui123** [comment]
And I wouldn't remove it, because the command name says what it does, so you don't need a true.

**Comment by DenielWorld** [comment]
True, but I am basing the plugin off of 98% vanilla commands, from here https://minecraftbedrock.fandom.com/wiki/Commands/List_of_Commands
Feel free to implement any command from here, besides /playsound, I am working on that already :D. I'll merge the PR now.

**Comment by Wertzui123** [comment]
Okey

**Pull request merged**
