### PR TITLE
WIP PlayerSelecotor

### PR DESCRIPTION
**Pull request by provsalt**
Adding @a @e @p and @s to commands
Not tested yet
@e and @p are to do.I only edited 1 file to see if deniel would take in this pr lmao.

### CODE REVIEW

**Comment by DenielWorld** [comment]
Do a proper implementation of it, and then I'll consider merging it. What you have right now is in no way finished.

**Review by DenielWorld — COMMENTED** [review]
Okay you could have at least considered starting on it before committing it. I am debating on whether I should use the existing PlayerSelector virion for this.

**Comment by provsalt** [comment]
if there is just use it lol.I didnt know there was such a virion thats why i made the  pr

**Comment by DenielWorld** [comment]
I made VanillaCommands pretty long ago, and looking back at it now it seems like a mess tbh. I don't know if I will ever be able to force myself to add updates to this, so if you want you can PR PlayerSelector support.

**Comment by DenielWorld** [comment]
Reopen this when you implement a proper implementation that was tested and functions right.

**Pull request closed without merging**
